name: Perl

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest , windows-latest]
        perl: [ '5.22', '5.36' ]
        # Strawberry Perl does not have 5.36 for now, but only 5.32
        exclude:
          - runner: windows-latest
            perl: '5.36'
        include:
          - runner: windows-latest
            perl: '5.32'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v3

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}

    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Modules
      run: |
        cpanm -V
        cpanm -v --installdeps --notest --with-recommends --with-suggests .

    - name: Run tests
      if:  ${{ !startsWith( matrix.runner, 'windows-')}}
      env:
        TEST_AUTHOR: 1
      run: |
        perl Makefile.PL
        make
        make test

    # On Windows there is no 'make' command. It seems that Makefile.PL defaults
    # to using 'dmake' which is maybe installed on the GitHub VMs. However we
    # know that there is a 'gmake' included with Strawberry Perl, so let’s use
    # that one.
    - name: Run tests on Windows
      if:  ${{ startsWith( matrix.runner, 'windows-')}}
      env:
        TEST_AUTHOR: 1
      run: |
        perl Makefile.PL MAKE=gmake
        gmake
        gmake test

    - name: Show Errors on Windows
      if:  ${{ failure() && startsWith( matrix.runner, 'windows-')}}
      run: |
         ls -l C:/Users/
         ls -l C:/Users/RUNNER~1/
         cat C:/Users/runneradmin/.cpanm/work/*/build.log

    - name: Show Errors on Ubuntu
      if:  ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
      run: |
         cat /home/runner/.cpanm/work/*/build.log

    - name: Show Errors on OSX
      if:  ${{ failure() && startsWith( matrix.runner, 'macos-')}}
      run: |
         cat  /Users/runner/.cpanm/work/*/build.log

